# -*- coding: utf-8 -*-
MOD_NAME = "StingerEngine"
SERVER_NAME = "StingerEngineServer"
CLIENT_NAME = "StingerEngineClient"

# UI 定义（JSON文件名.命名空间），供 @ScreenNodeWrapper.autoRegister 使用
MAIN_INTERFACE_UI_DEF = "MainInterfaceUI.MainInterfaceUI"
GAME_UI_DEF = "GameUI.GameUI"
ERROR_UI_DEF = "ErrorUI.ErrorUI"
SYSTEM_MENU_UI_DEF = "SystemMenuUI.SystemMenuUI"

UI_PUSH_DELAY = 0.05
SCRIPT_EXECUTION_STEP_LIMIT = 1024

SAVE_SCHEMA_VERSION = 1
SAVE_KEY_PREFIX = "stinger_save"
SAVE_SLOT_1_ID = "slot_1"
SAVE_SLOT_2_ID = "slot_2"
SAVE_SLOT_3_ID = "slot_3"
SAVE_MANUAL_SLOT_COUNT = 18
SAVE_SLOT_AUTO_ID = "slot_auto"
SAVE_SLOT_QUICK_ID = "slot_quick"
SAVE_CLIENT_CONFIG_NAME = "stinger_save_client_config"
SAVE_DEFAULT_QUICK_SAVE_KEY = "F5"
SAVE_DEFAULT_QUICK_LOAD_KEY = "F9"

SAVE_LIST_REQUEST = "SAVE_LIST_REQUEST"
SAVE_LIST_RESPONSE = "SAVE_LIST_RESPONSE"
SAVE_WRITE_REQUEST = "SAVE_WRITE_REQUEST"
SAVE_WRITE_RESPONSE = "SAVE_WRITE_RESPONSE"
SAVE_LOAD_REQUEST = "SAVE_LOAD_REQUEST"
SAVE_LOAD_RESPONSE = "SAVE_LOAD_RESPONSE"
SAVE_DELETE_REQUEST = "SAVE_DELETE_REQUEST"
SAVE_DELETE_RESPONSE = "SAVE_DELETE_RESPONSE"
SAVE_CONTINUE_QUERY = "SAVE_CONTINUE_QUERY"
SAVE_CONTINUE_RESPONSE = "SAVE_CONTINUE_RESPONSE"
